---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-app
  namespace: default
spec:
  selector:
    matchLabels:
      app: nginx-app
  replicas: 3
  template:
    metadata:
      labels:
        app: nginx-app
    spec:
      containers:
      - name: nginx-app
        image: nginx:latest
        imagePullPolicy: IfNotPresent
        lifecycle:
          preStop:
            exec: 
              command: ["sleep","60"]
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "200m"        
        ports:
        - containerPort: 80       
      #   volumeMounts:
      #   - mountPath: /etc/nginx/conf.d 
      #     readOnly: true
      #     name: nginx-conf
      # volumes:
      # - name: nginx-conf
      #   configMap:
      #     name: nginx-conf 
      #     items:
      #       - key: virtualhost.conf
      #         path: default.conf
---
kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2beta1
metadata:
  name: nginx-hpa
  namespace: default
spec:
  maxReplicas: 10
  minReplicas: 3
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nginx-app
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 70              
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: default
  labels:
    name: nginx-service
spec:
  selector:
    app: nginx-app
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 80    
